apiVersion: apps/v1
kind: Deployment
metadata:
  name: backendfeed
spec:
  selector:
    matchLabels:
      run: backendfeed
  replicas: 2
  template:
    metadata:
      labels:
        run: backendfeed
    spec:
      containers:
      - name: backendfeed
        image: docker.io/iniakponode/udagram-api-feed:v5
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 500m

---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: backendfeed
  name: backendfeed
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: backendfeed