apiVersion: apps/v1
kind: Deployment
metadata:
  name: backenduser
spec:
  selector:
    matchLabels:
      run: backenduser
  replicas: 2
  template:
    metadata:
      labels:
        run: backenduser
    spec:
      containers:
      - name: backenduser
        image: docker.io/iniakponode/udagram-api-user:v5
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 500m


---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: backenduser
  name: backenduser
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: backenduser