version: "3"
services:
  backenduser:
    image: docker.io/iniakponode/udagram-api-user:v20
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD 
      POSTGRES_DB: $POSTGRES_DB 
      POSTGRES_HOST: $POSTGRES_HOST
      AWS_REGION: $AWS_REGION 
      AWS_PROFILE: $AWS_PROFILE 
      AWS_BUCKET: $AWS_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: "http://localhost:8100"
    # networks:
    #   - example-net

  backendfeed:
    image: docker.io/iniakponode/udagram-api-feed:v20
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD 
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_HOST: $POSTGRES_HOST
      AWS_REGION: $AWS_REGION
      AWS_PROFILE: $AWS_PROFILE 
      AWS_BUCKET: $AWS_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: "http://localhost:8100"
    # networks:
    #   - example-net

  reverseproxy:
    image: docker.io/iniakponode/reverseproxy:v20
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - backenduser
      - backendfeed
    # networks:
    #   - example-net
          
  frontend:
    image: docker.io/iniakponode/frontend:v20
    ports:
      - "8100:80"
    # networks:
    #   - example-net

# networks:
#   example-net:
#     external: true