version: "3"
services:
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: docker.io/iniakponode/reverseproxy:v20
  backend_user:
    build:
      context: ./udagram-api-user
    image: docker.io/iniakponode/udagram-api-user:v20
  backend_feed:
    build:
      context: ./udagram-api-feed
    image: docker.io/iniakponode/udagram-api-feed:v20
  frontend:
    build:
      context: ./udagram-frontend
    image: docker.io/iniakponode/udagram-frontend:v20

# Make sure the Docker services are running in your local machine
# Remove unused and dangling images
# docker image prune --all
# Run this command from the directory where you have the "docker-compose-build.yaml" file present
# docker-compose -f docker-compose-build.yaml build --parallel
