version: 2.1

jobs:
  lint-app:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
  build-docker:
    machine: true
    steps:
      - checkout
      - run:
          name: Build docker container for each microservices
          command: |
            
            echo "-------- All images succesfully built----------"
            echo " ------- login in to hub--------"
            docker login -u iniakponode -p $DOCKERPASS
            echo "-------------- Pushing images to dockerhub-------"
            docker-compose -f docker-compose-build.yml push
workflows:
  default:
    jobs:
      - lint-app
      - build-docker:
          requires: [lint-app]